import React from "react";

function PortfolioAboutSection({ lightMode }) {
  return (
    <section className={``} style={{ opacity: "0.5" }}>
      <h2 className="fs-16-14 fw-600 mb-10">About Portfolio Analysis</h2>
      <h3 className="fw-600 fs-16-12">What is Portfolio Analysis?</h3>
      <p>
        Portfolio Analysis tool allows investors to check the performance of
        their portfolio at regular intervals. Portfolio Analysis tool offers a
        complete overview of the stocks held by the investor, including the name
        of each stock, the quantity of shares owned, the percentage of the
        portfolio each holding represents, as well as the profit or loss
        percentage associated with each stock. Additionally, it may provide
        various other metrics and insights to help investors make informed
        decisions about their investment strategy.
      </p>
      <h3 className="fw-600 fs-16-14 mb-10">
        Benefits of Portfolio Analysis -
      </h3>
      <p>
        <b> • Risk Assessment : </b>Portfolio analysis helps you assess and
        understand the risk exposure of your investments. This enables you to
        make more informed investment decisions aligned with your risk
        tolerance.
      </p>
      <p>
        <b> • Performance Evaluation : </b>Portfolio analysis tool allows you to
        evaluate the performance of your investments.{" "}
      </p>
      <p>
        <b> • Decision-making Support : </b>Portfolio analysis provides valuable
        insights and data-driven information to support your informed
        decision-making process.{" "}
      </p>
      <p>
        <b> • Goal Alignment : </b>Conducting portfolio analysis helps align
        your investments with your financial goals. Regularly reviewing your
        portfolio's performance and progress ensures that your investment
        strategy remains consistent with your objectives. Monitoring your
        portfolio allows you to make necessary adjustments, such as rebalancing
        or realigning asset allocations, to stay on track toward achieving your
        long-term goals.
      </p>
      <h3 className="fw-600 fs-16-14 mb-10">
        Features of Portfolio Analysis tool
      </h3>
      <p>
        <b>• Holdings- </b>The holdings section of Portfolio Analysis tool
        allows you to view a detailed breakdown of your holdings including the
        current market price of the shares that you hold, quantity of shares
        held by you, average price of each stock, percentage of each stock that
        you are holding, total value of your stocks and also know the
        profit/loss percentage of your stocks for detailed analysis.{" "}
      </p>
      <p>
        <b>• Heatmaps- </b>You can visualize the performance of your stock
        holdings through heatmaps of the Portfolio analysis tool that provides a
        rapid overview of the day's best and worst performing stocks in your
        portfolio.
      </p>
      <p>
        <b>• Top Best and Worst Performers- </b>The Portfolio Analysis tool
        allows investors to identify the top-performing and worst performing
        stocks that you have in your portfolio{" "}
      </p>
      <p>
        <b>• Sector Analysis and Industry Analysis- </b>Utilizing the sector
        analysis and industry analysis features of the Portfolio Analysis tool,
        you can assess the sectors and industries in which your stocks are held.
        This provides a clear perspective on the diversification of your
        portfolio.
      </p>
      <p>
        <b>• Dividends Payers List- </b>Using the dividends payers list, you can
        determine the estimated dividends you will receive from the stocks held
        in your portfolio.
      </p>
      <p>
        <b>• Fundamentals- </b>Fundamentals of Portfolio Analysis tool allows
        you to check the fundamentals of the stocks that you hold by dis
        different metrices such as PE, ROE, ROCE, current ratio and many more.
      </p>
      <p>
        <b>• Smart Score- </b>The Portfolio Analysis Tool's Smart Score
        evaluates a company on a scale of 1 to 5 across various metrices such as
        value, growth, profit, quality, performance, and ownership.
      </p>
      <p>
        <b>• Performance tracker- </b>You can monitor the quarterly performance
        of the stocks within your portfolio by utilizing the performance tracker
        feature of the portfolio analysis tool. This tracker measures quarterly
        performance based on metrics such as net sales, net profit, and profit
        margin.
      </p>
      <p>
        <b>• Research Reports- </b>The research reports generated by the
        Portfolio Analysis tool offers brokerage recommendations regarding
        whether to buy, sell, or hold the stocks currently held within your
        portfolio.{" "}
      </p>
    </section>
  );
}
export default PortfolioAboutSection;
