export const plans = {
  basic: {
    watchlist: 1,
    portfolioAnalsis: 0,
    stockCompare: 2,
    screener: 3,
    customScreener: 0,
    excel: 0,
    backtesting: 1,
  },
  // Bulls
  "1months": {
    watchlist: 3,
    portfolioAnalsis: 1,
    stockCompare: 3,
    screener: 10,
    customScreener: 3,
    excel: 50,
    backtesting: 3,
  },
  "3months": {
    watchlist: 3,
    portfolioAnalsis: 1,
    stockCompare: 3,
    screener: 10,
    customScreener: 5,
    excel: 50,
    backtesting: 1,
  },
  "12months": {
    watchlist: 5,
    portfolioAnalsis: 3,
    stockCompare: 4,
    screener: 20,
    customScreener: 500,
    excel: 100,
    backtesting: 9999,
  },
  "6months": {
    watchlist: 5,
    portfolioAnalsis: 3,
    stockCompare: 4,
    screener: 20,
    customScreener: 5,
    excel: 100,
    backtesting: 5,
  },
  "3years": {
    watchlist: 50,
    portfolioAnalsis: 5,
    stockCompare: 5,
    screener: 500,
    customScreener: 500,
    excel: 1000,
    backtesting: 9999,
  },
  year: {
    watchlist: 50,
    portfolioAnalsis: 5,
    stockCompare: 5,
    screener: 500,
    customScreener: 500,
    excel: 1000,
    backtesting: 9999,
  },
  lifetime: {
    watchlist: 50,
    portfolioAnalsis: 10,
    stockCompare: 5,
    screener: 500,
    customScreener: 500,
    excel: 1000,
    backtesting: 9999,
  },
  trial_plus: {
    watchlist: 50,
    portfolioAnalsis: 5,
    stockCompare: 5,
    screener: 500,
    customScreener: 500,
    excel: 1000,
    backtesting: 9999,
  },
  "3months_plus": {
    watchlist: 50,
    portfolioAnalsis: 5,
    stockCompare: 5,
    screener: 10,
    customScreener: 3,
    excel: 50,
    backtesting: 3,
  },
  "1month_plus": {
    watchlist: 3,
    portfolioAnalsis: 1,
    stockCompare: 3,
    screener: 10,
    customScreener: 3,
    excel: 50,
    backtesting: 3,
  },
  "6months_plus": {
    watchlist: 50,
    portfolioAnalsis: 5,
    stockCompare: 5,
    screener: 500,
    customScreener: 500,
    excel: 1000,
    backtesting: 9999,
  },
  year_plus: {
    watchlist: 50,
    portfolioAnalsis: 5,
    stockCompare: 5,
    screener: 500,
    customScreener: 500,
    excel: 1000,
    backtesting: 9999,
  },
  lifetime_plus: {
    watchlist: 50,
    portfolioAnalsis: 10,
    stockCompare: 5,
    screener: 500,
    customScreener: 500,
    excel: 1000,
    backtesting: 9999,
  },
};
